language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

# command to install dependencies

before_install:
  - python --version
  - pip install -U pip

install:
  - pip install ".[test]" . # install package + test dependencies
  - pip install -e .  # develop package
  - pip list

# command to run tests
script:
  - pytest --cov=. --verbose

# submit coverage
after_success:
  - codecov
